FROM node:18-alpine AS builder

WORKDIR /app

# 安装依赖
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile --network-timeout 300000

# 复制源码并构建
COPY . .
RUN DISABLE_ESLINT_PLUGIN=true GENERATE_SOURCEMAP=false yarn build

FROM scratch AS export
COPY --from=builder /app/build /
