server {
    listen 3003;
    server_name _;

    location /chat/assets/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    }

    location /chat/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /chat/index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
    }
}
